server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:h2:./db_cs;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # \uC7AC\uC2DC\uC791\uD558\uBA74 \uD14C\uC774\uBE14 \uC9C0\uC6B0\uACE0 \uB2E4\uC2DC \uB9CC\uB4E6. update \uC720\uC9C0.
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
#        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE