server:
  port: 8080

spring:
  datasource:
    url: "jdbc:h2:file:./data/coursedb"
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

logging:
  level:
    com.example.courserecommender: INFO

recommendations:
  file:
    path: "./data/recommended.txt"